### ISSUE TITLE
Show the current active challenge

### ISSUE THREAD

**Issue by javisperez** [x-team/the-vault#30]
If I just joined a channel or missed the challenge, would be really easy to just do something like `/challenge` and display the current active challenge, in the current channel.

Even if there's more than one challenge something like `/challenges` could be done and add some way to show the specific one (maybe `/challenges n` where n = 1,2,3...).

**Comment by keremgocen** [comment]
+1 for this feature, could turn out very useful when have even more quests to pick from

**Comment by ryanchartrand** [comment]
This is a phenomenal idea! It should also be something global, so that it pulls from all current active quests/challenges and lists out active challenges.

Here's the ideal scenario:

**Admin:**
Bot you can talk to:
Type "set challenge"
Q: What channel is this challenge for?
A: #fit-quest 
Q: What is the challenge?
A: Blah blah blah
Q: When is it due? dd/mm/yy
A: 15/11/2017



Type anywhere "/listQuests"
Receive: 
"Here are the active quests and current challenges for each:
*Fit-Quest* 
Current challenge: [display challenge]
Due date: [display due date]


Not sure if this belongs in The Vault or its own bot though.

**Comment by keremgocen** [comment]
@ryanchartrand would be ACE if you throw in an Hactoberfest label on this one

**Comment by jacekelgda** [comment]
You are on the point with this, great thinking @javisperez 👍

As @ryanchartrand pointed out it's most likely not to be mixed with The Vault itself but this is a much needed feature of something that is currently being discussed.

We should form a project that will inform X-Teamers about ongoing community initiatives in very clear way. Weather it will be in form of a slash command or bot as you suggested or some other form. I will loop you in when we figure out the most efficient form of this.

**Comment by jacekelgda** [comment]
@keremgocen the Hacktoberfest is ending Today so it might be a bit too late for that :)

**Comment by karolsojko** [comment]
Not sure if this is something that belongs in `The Vault` actually. We have http://community.x-team.com for this.

Even if you'd like that as a slack command - I'd suggest it belongs to a different project than the vault
