### ISSUE TITLE
Provide reason for coins being granted

### ISSUE THREAD

**Issue by jedrzej** [x-team/the-vault#33]
Sometimes when I'm granted a coin it's a bit hard to tell why I got it, especially when it happens some time after quest was ended. I think it would make sense to also provide user with a reason why they got coins. This would also allow easier tracking of coins history and help identify coins that should have been granted but haven't.

I'm thinking about `/grantcoins @user reason...` syntax.

I'll be happy to add that feature, just let me know if you also feel that's needed.

**Comment by karolsojko** [comment]
Good idea .. 👍 from me 

It'll always play well with the logs

**Comment by jacekelgda** [comment]
Yeah, go ahead @jedrzej 👍

**Comment by keremgocen** [comment]
Nice thinking, i think it'd be more convenient to have automated bulk coin distribution for a given quest's participants instead of expecting the admin to type an additional `reason` field for each coin given out.

That'd however require more work to keep track of an active quest's participant list and their ranking among the quest requirements.

Keeping a list per quest (as suggested previously) in the form of;

`{<count count>, <participant list>, <reason>, <quest>}` could be a much better investment I'm thinking.. Then the admin invoke the command `/end-quest <quest-name>/<quest-id>` to initiate the distribution.

`{3, '@kerem', '@jacek',  'participating in all challenges', 'fit-quest-1'}`

then the command `/end-quest fit-quest1` can give out the coins automatically and send messages to @kerem and @jacek saying;

>You have been awarded 3 x🏅 for participating in all challenges in fit-quest-1

**Comment by karolsojko** [comment]
seems to me like an overkill. I'd like to see the "reason" implemented at first and go the usual way `/grantcount @user1 @user2 @user3 "fit-quest"`

**Comment by keremgocen** [comment]
It is an overkill indeed, that's why it's fun:)

**Comment by jedrzej** [comment]
FYI, I'm working on another app to help users track quests - https://github.com/jedrzej/quest-bank. At some point we could try to combine both in order to get what @keremgocen mentioned, but I'd start simple for now as @karolsojko suggests.

**Comment by keremgocen** [comment]
>but I'd start simple for now as @karolsojko suggests.

These boys don't know how to have fun @jedrzej, although I agree it'll be a lot faster to implement that simple solution!
